### ISSUE TITLE
Error when reverting: Response object has no attribute code

### ISSUE THREAD

**Issue by bgirardot** [Zverik/simple-revert#15]
Reverting changesets: 60751388 60410078 60869071 60651116 60680367 60868463 60681244 60825467 60750473 60835495 60752411 60427603 
Comment: Reverts a change set that accidentally deleted important data
User: bgirardot
Added: 21.07.2018

Status: system error
Error: 'Response' object has no attribute 'code'

**Comment by Zverik** [comment]
Please try again, Blake. It must be an error with the API.

**Comment by ivanbranco** [comment]
I'm having the same problem [since yesterday](http://revert.osmz.ru/queue) with this [changeset](https://www.openstreetmap.org/changeset/130123907).

**Comment by Zverik** [comment]
Found and fixed the messaging error. Alas it was hiding another error that is even harder to trace: http://revert.osmz.ru/7957
